### ISSUE TITLE
404 when using download pretrained model script

### ISSUE THREAD

**Issue by jarricd** [sczhou/LEDNet#10]
There is a 404 (not found) error when using download_pretrained_models.py.
Command: `python3 download_pretrained_models.py LEDNet`

Result:
![image](https://user-images.githubusercontent.com/38395057/199663413-553a6962-53ab-4e81-8ca4-11b553101ce8.png)

**Comment by sczhou** [comment]
Manually download the model from [[Release V0.1.0](https://github.com/sczhou/LEDNet/releases/tag/v0.1.0)] to the weights folder
