### ISSUE TITLE
about lednet.pth and lednet_retrain_500000.pth

### ISSUE THREAD

**Issue by KKKLeouee** [sczhou/LEDNet#12]
Hello, your network, lednet.pth and lednet_ retrain_ 500000. pth These two networks are both through train_ Is LEDNet.yml the network for training?

What is the difference between the two? What adjustments are needed to obtain the two network models?

What type of machine was used in your training model at that time, and how many days would it take to train？
thank you

**Comment by sczhou** [comment]
The `lednet.pth` model is the version used in our paper and it was trained using a different framework. The `lednet_retrain_500000.pth` model, on the other hand, is a version retrained under the BasicSR framework, making it more practical for further development and usage. Both models were trained with similar settings, resulting in only minor differences between them. 

The training process for both models took around 2-3 days on one V100 GPU.
