### ISSUE TITLE
Default path in generate_low_light_imgs.py should be generic

### ISSUE THREAD

**Issue by jarricd** [sczhou/LEDNet#9]
The path in argument parse, file generate_low_ligh_imgs.py:
`parser.add_argument('--test_path', type=str, default='/mnt/lustre/sczhou/datasets/deblurring/LOLBlur/high_sharp_scaled')` should be generic and not include the developer's filesystem path.

If those arguments are required, it's a good practice not to include a default value, or provide a value that will work in all envirnoments.

**Comment by sczhou** [comment]
I think it should be common sense to change the input path while running a processing code.

**Comment by jarricd** [comment]
I don't agree. This a bad practice, system-specific paths should not be pushed to a public repo.
